name: test

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
    
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # v3.0.3
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # v3.0.3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
